# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5 import QtCore,QtWidgets
from PyQt5.QtWidgets import QApplication,  QFileDialog
from PIL import Image
from PyQt5.QtGui import QImage,QPixmap
from frcnn import FRCNN
import tensorflow as tf
import numpy as np
gpus = tf.config.experimental.list_physical_devices(device_type='GPU')


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(942, 702)
        self.centralwidget = QtWidgets.QWidget(Form)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 100, 400, 400))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(490, 100, 400, 400))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(350, 30, 400, 60))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(130, 630, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(590, 630, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(30, 530, 871, 91))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.pushButton.clicked.connect(self.openimg)
        self.pushButton_2.clicked.connect(self.detect)

    def openimg(self):
        self.img_file, _ = QFileDialog.getOpenFileName(self.centralwidget, 'Open file',
                                                       r'data//voc//VOCdevkit//VOC2007//JPEGImages',
                                                       'Image files (*.jpg)')
        print(self.img_file)
        self.img = QPixmap(self.img_file)
        self.label.setPixmap(self.img)
        self.label.setScaledContents(True)

    def detect(self):
        image = Image.open(self.img_file)
        frcnn = FRCNN()
        crop = False
        count = False
        r_image,a = frcnn.detect_image(image, crop=crop, count=count)
        image_array = np.array(r_image)
        label_width = self.label_2.width()
        label_height = self.label_2.height()
        temp_imgSrc = QImage(image_array, image_array.shape[1], image_array.shape[0], image_array.shape[1] * 3,
                             QImage.Format_RGB888)
        pixmap_imgSrc = QPixmap.fromImage(temp_imgSrc).scaled(label_width, label_height)
        print(image_array)
        self.label_2.setPixmap(pixmap_imgSrc)
        self.textEdit.append('标签和置信度:%s' % a[0])
        self.textEdit.append('top:%s'%a[1])
        self.textEdit.append('left:%s' %a[2])
        self.textEdit.append('bottom:%s' %a[3])
        self.textEdit.append('right:%s' % a[4])

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "玻璃瓶口检测系统"))
        self.label.setText(_translate("Form", "TextLabel"))
        self.label_2.setText(_translate("Form", "TextLabel"))
        self.label_3.setText(_translate("Form", "玻璃瓶口检测系统"))
        self.pushButton.setText(_translate("Form", "导入图片"))
        self.pushButton_2.setText(_translate("Form", "开始检测"))
if __name__ == '__main__':
    import PyQt5
    app = QApplication(sys.argv)
    ex = Ui_Form()
    window = PyQt5.QtWidgets.QMainWindow()
    ex.setupUi(window)
    window.show()
    sys.exit(app.exec_())